apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: mychart
data:
  myvalue: "hello world"
  drink: {{ .Values.favoriteDrink | upper | quote }}
  {{- if eq .Values.favoriteDrink "coffee" }}
  mug: true
  {{- end }}
