apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: mychart
data:
  myvalue: "hello world"
  drink: {{ .Values.favorite.drink | upper | quote }}
  {{- if eq .Values.favorite.drink "coffee" }}
  mug: true
  {{- end }}
  {{- with .Values.favorite }}
  favorite: {{ .food }}
  {{- end}}
  toppings: |-
    {{- range .Values.pizzaToppings }}
    - {{ . }}
    {{- end }}
  pastas: |-
    {{- range $index, $value := .Values.pizzaToppings }}
      {{ $index }}: {{ $value }}
    {{- end }}
